// Generated by `supabase gen types typescript --linked > src/lib/database.types.ts`
// (we use the MCP `generate_typescript_types` tool in practice).
// Re-export the Database type plus a few convenience aliases for query results.
export type { Database, Json } from "../database.types";

import type { Database } from "../database.types";

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type Updates<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
